const INVOICE_STATUS = Object.freeze({
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  EXTRACTION_REQUIRED: 'EXTRACTION_REQUIRED',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
  APPROVED_BY_CLIENT: 'APPROVED_BY_CLIENT',
  SIGNING: 'SIGNING',
  WAITING_TTN: 'WAITING_TTN',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  ERROR: 'ERROR',
});

const RETRYABLE_STATUSES = Object.freeze([
  INVOICE_STATUS.REJECTED,
  INVOICE_STATUS.WAITING_TTN,
  INVOICE_STATUS.ERROR,
]);

module.exports = {
  INVOICE_STATUS,
  RETRYABLE_STATUSES,
};